import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <section className='flex w-screen h-screen'>
          <div className='flex justify-center w-2/3 mx-auto my-auto'>
            <div className='flex flex-col'>
              <div className='flex w-full'>
                <h1 className='font-mono font-semibold text-7xl'>Duane Scarlett</h1>
              </div>
              <div className='flex w-full'>
                <code className='ml-4 font-semibold text-teal-300'>React | Node | DevOps | Blockchain | Solidity | Full-Stack</code>
              </div>
            </div>
          </div>
        </section>
        <section className='flex w-screen h-screen'>
          <div className='flex justify-center w-2/3 mx-auto my-auto'>
            <div className='flex flex-col'>
              <div className='flex justify-start'>
                <h1 className='font-mono font-semibold text-7xl'>Who am I?</h1>
              </div>
              <div className='flex w-2/3 justify-center'>
                <code className='flex flex-col text-xl'>
                  <p className='mt-6 text-teal-300 hover:text-sky-200'>
                    I am a Software Engineer and Blockchain developer 
                    with over 12 years of experience in the tech industry. 
                    I enjoy all aspects of Information Technology from 
                    UI/UX to System Administration. I am a true Full-Stack 
                    Software Engineer. Currently I am particularly fond 
                    of bringing Blockchain solutions to business development.
                  </p>
                  <button className='flex justify-slef-start mt-10 w-[180px] px-auto text-center'>
                    Let's Connect
                  </button>
                </code>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
